spring:
  application:
    name: c-student
 
server: 
  port: 8091
  
eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
      # defaultZone: http://test:abc123@localhost:8761/eureka
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

cluster1:
  gateway:
    url: ${CLUSTER1_GATEWAY_URL}
    # url: http://localhost:8888
  