spring:
  application:
    name: e-school
 
server: 
  port: 8083
  
eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
      # defaultZone: http://test:abc123@10.9.0.12:8761/eureka
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

cluster2:
  gateway:
    url: ${CLUSTER2_GATEWAY_URL}
    # url: http://10.9.0.12:28083
