server:
  port: 8888

spring:
  application:
    name: zuul-gateway

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
zuul:
  routes:
    e-school: 
      path: /api-e/**
      serviceId: e-school
    d-score: 
      path: /api-d/**
      serviceId: d-score

# eureka:
#   client:
#     serviceUrl: 
#       defaultZone: ${EUREKA_URL}
#       # defaultZone: http://localhost:8762/eureka/
#   instance:
#     # 优先使用IP地址方式进行注册服务
#     prefer-ip-address: true

# zuul:
#   routes:
#     c-student: 
#       path: /api-c/**
#       serviceId: c-student