apiVersion: v1
kind: Namespace
metadata:
  name: flomesh-poc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
    project: poc
  name: eureka-server
  namespace: flomesh-poc
spec:
  ports:
  - name: app
    nodePort: 31000
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server
    project: poc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: flomesh-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      project: poc
      app: eureka-server
  template:
    metadata:
      labels:
        project: poc
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: spurringworld/eureka-server:v1.1
        imagePullPolicy: IfNotPresent
