apiVersion: v1
kind: Namespace
metadata:
  name: flomesh-poc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-gateway
    project: poc
  name: zuul-gateway
  namespace: flomesh-poc
spec:
  ports:
  - name: app
    nodePort: 31001
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: zuul-gateway
    project: poc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-gateway
  namespace: flomesh-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      project: poc
      app: zuul-gateway
  template:
    metadata:
      labels:
        project: poc
        app: zuul-gateway
    spec:
      containers:
      - name: zuul-gateway
        image: spurringworld/zuul-gateway:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: EUREKA_URL
          value: "http://10.9.0.7:31000/eureka"
