spring:
  application:
    name: c1-club
 
server: 
  port: 8092
  
eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
      # defaultZone: http://test:abc123@localhost:8761/eureka
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
    metadata-map:
      upstream_version: 2.0.0