spring:
  application:
    name: f-teacher
 
server: 
  port: 8084
  
eureka:
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
      # defaultZone: http://test:abc123@localhost:8761/eureka
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

service-g:
  url: ${SERVICE_G_URL}
  